sudo: required
dist: trusty
language: node_js
node_js:
  - '10.0.0'

install:
  - npm install

script:
  - npm run build-ts
  - npm run lint
  - npm test

# before_script:
#   - ganache-cli > /dev/null &
#   - sleep 5